name: Deploy to Server

on:
  push:
    branches:
      - main # Убедитесь, что ваша главная ветка называется main (а не master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/SynthLab
            git fetch --all
            git reset --hard origin/main
            git clean -fd
            cd synth-app
            npm install
            npm run build
            # Перезапуск PM2 с явным указанием порта из конфига
            pm2 delete synth-generator || true
            pm2 serve dist 9000 --name "synth-generator" --spa
