name: Deploy to Server

on:
  push:
    branches:
      - main # Убедитесь, что ваша главная ветка называется main (а не master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/SynthLab/synth-app
            git pull
            npm install
            npm run build
            # Пересоздаем процесс PM2, чтобы он точно смотрел в новую папку dist
            pm2 delete synth-generator || true
            pm2 serve dist 9000 --name "synth-generator" --spa
